### PR TITLE
feat: update to Pest v2

### PR DESCRIPTION
**Pull request by johanmolen**
Based on https://github.com/laravel/installer/pull/262/files.

### CODE REVIEW

**Comment by innocenzi** [comment]
This won't work because `pest --init` doesn't support `--no-interaction` anymore it seems. Will have to PR again.

**Comment by johanmolen** [comment]
I tried this flow but it worked for me, the Laravel installer does it the same way.

**Comment by johanmolen** [comment]
I tried this flow but it worked for me, the Laravel installer does it the same way.

**Comment by innocenzi** [comment]
Tried myself and it didn't work, it hangs at `setup Pest`. But I'll update Preset to support custom environment variables so we can set [`PEST_NO_SUPPORT`](https://github.com/pestphp/pest/blob/50a96dcb8f4dd219b09d216d844e435ab1609f90/src/Console/Thanks.php#L51).

Honestly they're doing a lil bit of forcing with this prompt.

**Comment by johanmolen** [comment]
Weird! I tried the Laravel Installer first, might be that `PEST_NO_SUPPORT` was still active in my terminal session or something?

All of that for a Github star 😂

**Comment by innocenzi** [comment]
Yeah, I really don't understand how pushy they are, but it is what it is. Thanks for the PR!

**Pull request merged**
